### ISSUE TITLE
well here ya go lmao 

### ISSUE THREAD

**Issue by ghost** [MelonIs45/osuThumbnailMaker#2]
C:\Users\keple\OneDrive\Desktop\osuThumbnailMaker-1.0.1\main.py:112: DeprecationWarning: scipy.product is deprecated and will be removed in SciPy 2.0.0, use numpy.product instead
  ar = ar.reshape(scipy.product(shape[:2]), shape[2]).astype(float)
C:\Users\keple\OneDrive\Desktop\osuThumbnailMaker-1.0.1\main.py:118: DeprecationWarning: scipy.histogram is deprecated and will be removed in SciPy 2.0.0, use numpy.histogram instead
  counts, bins = scipy.histogram(vecs, len(codes))
C:\Users\keple\OneDrive\Desktop\osuThumbnailMaker-1.0.1\main.py:119: DeprecationWarning: scipy.histogram is deprecated and will be removed in SciPy 2.0.0, use numpy.histogram instead
  counts2, bins2 = scipy.histogram(vecs2, len(codes2))
C:\Users\keple\OneDrive\Desktop\osuThumbnailMaker-1.0.1\main.py:120: DeprecationWarning: scipy.argmax is deprecated and will be removed in SciPy 2.0.0, use numpy.argmax instead
  index_max = scipy.argmax(counts)
C:\Users\keple\OneDrive\Desktop\osuThumbnailMaker-1.0.1\main.py:121: DeprecationWarning: scipy.argmax is deprecated and will be removed in SciPy 2.0.0, use numpy.argmax instead
  index_max2 = scipy.argmax(counts2)
Traceback (most recent call last):
  File "C:\Users\keple\OneDrive\Desktop\osuThumbnailMaker-1.0.1\main.py", line 222, in <module>
    rankImage = Image.open("ranks/{}.png".format(playRank))
  File "C:\Python39\lib\site-packages\PIL\Image.py", line 2975, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'ranks/SH.png'

**Comment by MelonIs45** [comment]
oh woops, i forgot to include the rank files when updating a release, ive updated it just now and you just redownload it xD
